namespace Anjoz.Identity.Utils.Tests.Utils
{
    public class LoginUtils
    {
        public const string Token = "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJ0ZXN0ZTEiLCJSRVNPVVJDRV9QRVJNSVNTSU9OUyI6WyJWQUxVRTEiLCJWQUxVRTIiLCJWQUxVRTMiLCJWQUxVRTQiLCJWQUxVRTUiXSwibmJmIjoxNTczNTE1NDc2LCJleHAiOjE1NzM1Mjc2MDAsImlhdCI6MTU3MzUxNTQ3Nn0.oGnH71MIqalOLBhXdHUfs1lYpyHFalYWaAC6dmlfvJzr0DjXZR_vV4UY91VbdXDwG5Va7_Bx4il1OiM0M0yxAw";
    }
}